services:
  - docker

script:
  - export REPO=j12934/defect-dojo
  - export TAG=$(echo $TRAVIS_BRANCH | sed 's/\//-/g')
  - echo -en "travis_fold:start:Docker_Build\r"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $REPO:$TAG .
  - echo -en "travis_fold:end:Docker_Build\r"
  - docker images

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deployDockerHub.sh
    on:
      all_branches: true
